frontend:
  - any:
      - "FrontEnd/**"

backend:
  - any:
      - "backend/**"

database:
  - any:
      - "database/**"

documentation:
  - any:
      - "*.md"
      - "docs/**"

config:
  - any:
      - ".github/**"
      - "**/application*.yml"
      - "**/application*.properties"